name: lwnode actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_lwnode:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        config: [ '', '--nopt --shared' ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout Escargot
        run: |
          pushd deps/escargot
          git submodule update --init third_party
          popd
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y ninja-build gcc-multilib g++-multilib sed
      - name: Build lwnode
        run: |
          ./configure.py ${{ matrix.config }}
          ninja -C out/linux/Release lwnode
      - name: Run node.js TCs (test.py)
        run: |
          pushd $(pwd)/deps/node
          ./tools/test.py \
            -J -p dots --report --time --timeout 240 --repeat 1 \
            --shell=../../out/linux/Release/lwnode \
            --skip-tests=$(sed 's/\s#.*//g' test/skip_tests.txt | paste -sd,) \
            --unsupported-tests=$(sed '/#\|^$/d' test/skip_features.txt | paste -sd,) \
            test/parallel test/regression
          popd
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 60

  cctest:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Checkout Escargot
        run: |
          pushd deps/escargot
          git submodule update --init third_party
          popd
      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y ninja-build gcc-multilib g++-multilib
      - name: Build cctest
        run: |
          export ROOT=$PWD
          export OUT_PATH=$ROOT/out/cctest
          export ARCH="x64"
          export ASAN=1
          export GYP=deps/node/tools/gyp/gyp
          $GYP ./test/cctest.gyp --depth=. -f ninja \
            --generator-output=$OUT_PATH -Dasan=$ASAN -Descargot_build_mode=debug \
            -Descargot_lib_type=static_lib -Dtarget_arch=$ARCH -Dtarget_os=linux \
            -Denable_experimental=true -Descargot_threading=1 \
            -Descargot_debugger=0
          ninja -C $OUT_PATH/out/Debug cctest
      - name: Run cctest
        run: |
          out/cctest/out/Debug/cctest
